Repository ML-Fusion-Lab/ML-Fusion-Lab-Website, pull requests merged in 2024-10, with the labels that each got.

#12 Improve Home Page
  index.html
  style.css
Labels: level2, gssoc-ext

#16 Add favicon
  about.html
  contact.html
  courses.html
  index.html
  ml-fusion-lab-logo.png
  privacy.html
  projects.html
  terms.html
Labels: level1, gssoc-ext

#17 Formatted "About ML fusion" differently
  index.html
  style.css
Labels: level1, gssoc-ext

#22 #4-issue(Fix Navbar)
  Assets/close-button.svg
  Assets/sidebar-menu-ham.svg
  index.html
  style.css
Labels: level2, gssoc-ext

#24 Header updated
  courses.html
  index.html
  style.css
Labels: level1, gssoc-ext

#25 Issue #14
  index.html
  style.css
Labels: level2, gssoc-ext

#61 Enhance Courses section with details and update Footer design
  about.html
  contact.html
  courses.html
  index.html
  intr-to-ml.html
  privacy.html
  projects.html
  style.css
  terms.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#64 added few more projects and fixed the allignment #54
  index.html
  projects.html
Labels: level2, gssoc-ext

#62 Scroll button added
  about.html
  contact.html
  courses.html
  index.html
  projects.html
  scroll.css
  scroll.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#56 issue #40; Solution : Updated Website Logo in Navigation Bar
  index.html
  ml fusion lab log.jpg
  ml fusion lab logo.jpeg
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#68 fixes footer and email text
  index.html
Labels: level1, gssoc-ext

#81 created a community-support.html
  community_suport.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#103 Updated Footer Links on Privacy Page to Match Website Theme
  privacy.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#105 Updated dark and light theme mode
  .vscode/settings.json
  Assets/moon.png
  Assets/sun.png
  about.html
  contact.html
  courses.html
  index.html
  privacy.html
  projects.html
  script.js
  style.css
  terms.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#69 Fix nav alignment, about section contrast and layout issue. Fixes #59
  about.html
  contact.html
  courses.html
  index.html
  projects.html
  style.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#57 About us page is complete
  about.html
  style.css
Labels: level2, gssoc-ext

#146 added more projects in projects.html code
  projects.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#149 Add Social Media Icons to Footer on all Pages
  about.html
  contact.html
  courses.html
  index.html
  projects.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#155 contact form submission functionality added
  contact.html
  index.html
  script.js
Labels: level2, gssoc-ext

#162 : Responsive Design and Content Overflow Issue #133
  index.html
Labels: level2, gssoc-ext

#154 changes to nav bar and logo on every tabs is done for issue #45
  about.html
  contact.html
  courses.html
  intr-to-ml.html
  privacy.html
  projects.html
  style.css
  terms.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#178 Project page has been updated #150
  projects.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#203 Created Issue and Pull-Request Template(ezDecode#200)
  .github/ISSUE_TEMPLATE/bugs.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
  .github/workflows/greetings.yaml
Labels: level1, gssoc-ext

#195 Fixed the footer in well organised and change the mail prompt to dark
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#138 Text readability and text overlapping figured out.
  style.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#212 Repetitive Content and Poor Engagement on the Homepage
  index.html
  style.css
Labels: level1, gssoc-ext

#222 A minimum character message limit validation enforced to contact us
  contact.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#215 Fixed ui and speed
  index.html
  scroll.css
Labels: level2, gssoc-ext

#229 Added Feedback page
  feedback.html
  index.html
Labels: level2, gssoc-ext

#239 Update the Design of "ML Fusion Labs" Section #172
  .github/ISSUE_TEMPLATE/bugs.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
  .github/workflows/greetings.yaml
  .vscode/settings.json
  index.html
  style.css
Labels: level1, gssoc-ext

#179 fixed #120 : Add Clickable Link to Logo Redirecting to Home Page #120
  about.html
  contact.html
  courses.html
  index.html
  projects.html
Labels: level1, gssoc-ext

#261 feedback page update
  feedback.html
Labels: level1, gssoc-ext

#268 Feature project update
  projects.html
Labels: level1, gssoc-ext

#272 Feature add user testimonial(#100)
  .hintrc
  Testimonial.html
  about.html
  community_suport.html
  contact.html
  courses.html
  index.html
  intr-to-ml.html
  privacy.html
  projects.html
  terms.html
Labels: level2, gssoc-ext

#278 Enhancements and Improvements for Community Support Page
  community_suport.html
  index.html
Labels: level2, gssoc-ext

#282 Dark Theme Updated Issue no #244 Resolved
  style.css
Labels: level1, gssoc-ext

#292 Added Images to the Project Cards
  Assets/projectpics/bot.png
  Assets/projectpics/cnn.png
  Assets/projectpics/crops.jpg
  Assets/projectpics/disease.jpg
  Assets/projectpics/dist.jpg
  Assets/projectpics/emai.jpg
  Assets/projectpics/eneryg.png
  Assets/projectpics/fraud.png
  Assets/projectpics/lth.png
  Assets/projectpics/mental.jpg
  Assets/projectpics/nut.jpg
  Assets/projectpics/personalizd.jpg
  Assets/projectpics/rec.jpg
  Assets/projectpics/shop.jpg
  Assets/projectpics/sound.jpg
  Assets/projectpics/stock.jpg
  Assets/projectpics/the.jpg
  Assets/projectpics/traffic.jpg
  Assets/projectpics/waste.jpg
  Assets/projectpics/wild.jpg
  projects.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#294 Updated Footer of whole website
  Testimonial.html
  about.html
  community_suport.html
  contact.html
  courses.html
  index.html
  intr-to-ml.html
  privacy.html
  projects.html
  terms.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#308 Resolved Logo Display Issue in community_support.html
  community_suport.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#315 Fixed toggle issue for Learn More button in course section
  intr-to-ml.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#316 Solved issue #303, successfully added dark-mode to the testimonial section
  Testimonial.html
  style.css
Labels: level1, gssoc-ext

#306 navbar position fixed
  index.html
  style.css
Labels: level2, gssoc-ext

#321 Added Back Button To Feedback Page
  feedback.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#326 Refactor CSS import and add direct course jump-in section
  index.html
  style.css
Labels: level2, gssoc-ext

#330 The contact page has been updated
  contact.html
Labels: level1, gssoc-ext

#343 Distorted Footer on the Course Page in ML Fussion #324
  course.css
  courses.html
Labels: level1, gssoc-ext

#341 Twitter logo changed to x
  about.html
  contact.html
  index.html
Labels: level1, gssoc-ext

#296 made changes in the project section's pop-up message- text rendering issue.
  projects.html
Labels: level1, gssoc-ext

#347 About section modified
  about.css
  about.html
  algorithm-3859537_1280.jpg
  never-stop-learning-3653430_1280.jpg
  programming-2115930_1280.jpg
  robot-2301646_1280.jpg
  style.css
  teammate1.jpg
  teammate2.jpg
  teammate3.jpg
  teammate4.jpg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#350 Update contact.html
  contact.html
Labels: level1, gssoc-ext

#353 Styled the scroll to top button in all pages
  about.html
  community_suport.html
  contact.html
  course.css
  courses.html
  privacy.html
  projects.html
  terms.html
Labels: level2, gssoc-ext

#354 Add load more button
  courses.html
  courses.js
  projects.html
  projects.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#376 added transitions effects to the input
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#377 Alignment issue of footer is solved also made it responsive
  about.css
  about.html
Labels: level1, gssoc-ext

#387 Background image added in dark mode
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#413 Github Bot_Added
  .github/workflow/greetings.yml
Labels: level1, gssoc-ext, hacktoberfest-accepted

#420 Updates the about us page in the website
  about.html
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#418 Correctly added workflow
  .github/ISSUE_TEMPLATE/bugs.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
  .github/workflows/greetings.yaml
Labels: level1, gssoc-ext, hacktoberfest-accepted

#421 Update community_suport.html
  community_suport.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#428 Update twitter icon
  Testimonial.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#437 Completed `Resource Library Section`
  image/data science.png
  image/r1.png
  image/r2.png
  image/r3.jpg
  image/r4.jpg
  image/r5.jpg
  image/r6.jpg
  resources.css
  resources.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#439 The community section #331
  community_suport.html
Labels: level1, gssoc-ext

#440 Added Course details page
  courseDetails.js
  course_details.css
  course_details.html
  courses.html
  courses.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#446 making contact form more dynamic
  contact.html
Labels: level2, gssoc-ext

#454 favicon fix
  about.html
Labels: level1, gssoc-ext

#449 Responsiveness of home Page(issue#410)
  style.css
Labels: level1, gssoc-ext

#455 Changed Feedback Form Page
  feedback.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#452 Completed `Mentor Page` of Community Section
  Course Assets/x.png
  image/m1.jpg
  image/m2.jpg
  image/m3.jpg
  mentor_program.css
  mentor_program.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#456 fixes: Projects Cards Overlapping – Add Padding/Gaps Between Project Cards #394
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#459 Added newsletter subscription confirmation message
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#463 Added Mouse Cursor Trail Effect
  Testimonial.html
  about.css
  about.html
  community_suport.html
  course_details.css
  course_details.html
  courses.html
  courses.js
  index.html
  intr-to-ml.html
  mentor_program.css
  mentor_program.html
  privacy.html
  projects.html
  projects.js
  resources.css
  resources.html
  script.js
  terms.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#470 improved UI of the form
  feedback.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#471 ImgUpdateInCourses.html
  Course Icons/autonomous-system.png
  Course Icons/business.png
  Course Icons/cloud-computing.png
  Course Icons/data-science.png
  Course Icons/programming-language.png
  courses.html
Labels: level1, gssoc-ext

#483 Added `QnA Section` in Community Part
  community_suport.html
  qa-schedule.css
  qa_schedule.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#489 Added Map in contact page
  contact.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#491 Added `Forum Section`
  community_suport.html
  forum.css
  forum.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#494 Updated twitter logo
  projects.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#486 fixes: Course Cards Layout Problem on /courses Route #478
  Course Icons/cloud computing.png
  Course Icons/programming language.png
  course.css
  courses.html
  image/data science.png
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#497 Update privacy policy and terms UI
  privacy.html
  style.css
  terms.html
Labels: level2, gssoc-ext

#501 fixed the banner background image of about us page
  style.css
Labels: level1, gssoc-ext

#498 Added Contributor's Page
  contributor.css
  contributor.html
  contributor.js
  index.html
  style.css
Labels: level3, gssoc-ext

#506 Created the social_media.html file for the community page #442
  community_suport.html
  social_media.html
Labels: level1, gssoc-ext

#507 contact page logo linked with home page.
  contact.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#510 Fixed issue no. #508 Home page logo and contact page, testimonials page logo are different.
  contact.html
  course.css
  courses.html
  style.css
Labels: level1, gssoc-ext

#511 ADDED THE LOGIN SIGN UP PAGE
  4emu.gif
  index.html
  login.css
  login.html
  login.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#513 Progress Par Implemented
  Testimonial.html
  about.html
  community_suport.html
  contact.html
  contributor.html
  course_details.html
  courses.html
  index.html
  intr-to-ml.html
  mentor_program.html
  privacy.html
  projects.html
  qa_schedule.html
  resources.html
  script.js
  style.css
  terms.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#518 Footer aligned properly
  social_media.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#516 [Feat] : Added Tensorflow Project Page to ML Fusion Lab Website
  Assets/projectpics/dog.png
  Assets/projectpics/dog_output.png
  dog_breed_classifier.html
  projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#534 ContactUs page updated
  Assets/contact.webp
  contact.css
  contact.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#541 fixed the issue of project overlapping
  projects.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#544 automatic focus of cursor is added
  courses.html
  courses.js
Labels: level1, gssoc-ext

#551 Embedded Links In `Our Features` Section of home page
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#552 search bar functionality updated in course section
  courses.js
Labels: level1, gssoc-ext

#553 Added a Cookie Consent Pop-up
  index.html
Labels: level2, gssoc-ext

#558 ADDED THE FEATURE OF LANGUAGE TRANSLATION
  Testimonial.html
  about.html
  community_suport.html
  contact.html
  courses.html
  feedback.html
  index.html
  projects.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#560 #536 issue resolved (adding toggle button in contact Us page)
  contact.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#561 Image Aligned properly.
  style.css
Labels: level1, gssoc-ext

#563 animation on projects
  projects.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#566 Scroll to top function visible bug fixed
  index.html
Labels: level1, gssoc-ext

#570 UPDATED README.md FILE WITH ALL THE CHANGES
  README.md
  gssocextd.jpg
  haaaaack.jpg
Labels: documentation, gssoc-ext, hacktoberfest-accepted

#578 improved scrolling and added back to top button on feedback page
  feedback.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#584 Added Filter courses
  course.css
  course_details.css
  course_details.html
  courses.html
  courses.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#585 #568 solved(Updated feedback form page)
  feedback.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#587 Using_Trusted_Mail_Services_For_Signup
  login.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#590 Password_Requirements_Updated_For_Signup
  login.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#592 Added CNN Tutorial for Paddy Disease Classification
  Assets/projectpics/paddy.jpeg
  paddy_disease_tutorial.html
  projects.html
  projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#602 for issue#591, Updated privacy.html
  privacy.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#603 Issue :-#598 Solved -- Pop up Functionality Added
  image/popup.jpg
  image/popup1.png
  image/popup2.png
  index.html
  script/popup.js
  style/popup.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#615 Alignment of subscribe button
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#619 Privacy page CSS updated
  pages/privacy.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#624 toggle button functionality added
  index.html
  pages/Testimonial.html
  pages/about.html
  pages/community_suport.html
  pages/projects.html
  style/style.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#628 ✨issue #627 solved , storage added✨
  .vscode/settings.json
  pages/feedback.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#634 Feat: Added crop height estimation project in project page
  pages/crop_height_estimation_tutorial.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#629 Enhance Courses #556
  pages/courses.html
  style/course.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#635 Aligned 'Learn more' button in Projects & 'tags' in Courses Section
  pages/projects.html
  script/projects.js
  style/course.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#637 Update contact.css
  style/contact.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#638 Added Tutorial page explaining Terrain Classification
  Assets/projectpics/terrain_classifier.jpg
  pages/projects.html
  pages/terrain_classifier.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#643 Update feedback.html
  pages/feedback.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#645 [Enchancement] Card Bug and Improved Project Button Functionality
  pages/projects.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#648 #632 Solved : Added Forgot password functionality
  pages/login.html
  script/forgotpassword.js
  script/login.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#647 ADDED THE NEW FONT FOR ALL THE PAGES
  style/about.css
  style/contact.css
  style/contributor.css
  style/course.css
  style/course_details.css
  style/forum.css
  style/login.css
  style/mentor_program.css
  style/popup.css
  style/qa-schedule.css
  style/resources.css
  style/scroll.css
  style/style.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#651 #650 CHanged hover colour success
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#654 Made `footer` of all page same
  pages/contact.html
  pages/feedback.html
  pages/projects.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#656 added github icon
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#660 Issue:- #652 Solved:- Added Air Quality Predictor
  Assets/projectpics/airquality.png
  CourseAssets/13.png
  CourseAssets/14.png
  pages/Air_Quality_Prediction.html
  pages/air_quality_code.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#663 update alignment of contributor page, project page, course page & update functionality of newsletter
  index.html
  pages/projects.html
  style/contributor.css
  style/course.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#664 Some Changes in index.html file
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#668 #622 solved (Testimonial Updated)
  pages/Testimonial.html
  pages/script/contributor.js
  pages/script/courseDetails.js
  pages/script/courses.js
  pages/script/forgotpassword.js
  pages/script/login.js
  pages/script/popup.js
  pages/script/projects.js
  pages/script/script.js
  pages/script/scroll.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#670 Added a Tutorial for Decision Tree Algorithm
  Assets/projectpics/decision_graph.png
  Assets/projectpics/decision_tree.svg
  Assets/projectpics/irish.jpg
  pages/decision_tree_tutorial.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#674 Some Changes in style.css file
  index.html
  style/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#676 RECOVERED THE JS FILES AND FIXED THE DARK MODE TOGGLE
  pages/course_details.html
  script/contributor.js
  script/courseDetails.js
  script/courses.js
  script/login.js
  script/script.js
  script/scroll.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#678 fixed the issue of invisibility
  pages/Testimonial.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#679 Fix/copyright year
  index.html
  pages/Air_Quality_Prediction.html
  pages/Testimonial.html
  pages/about.html
  pages/community_suport.html
  pages/contact.html
  pages/contributor.html
  pages/course_details.html
  pages/courses.html
  pages/crop_height_estimation_tutorial.html
  pages/dog_breed_classifier.html
  pages/feedback.html
  pages/forum.html
  pages/intr-to-ml.html
  pages/mentor_program.html
  pages/paddy_disease_tutorial.html
  pages/privacy.html
  pages/projects.html
  pages/qa_schedule.html
  pages/resources.html
  pages/social_media.html
  pages/terms.html
  pages/terrain_classifier.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#685 [FIX] "Scroll to Top" Button and CSS of projects
  pages/Air_Quality_Prediction.html
  pages/crop_height_estimation_tutorial.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#686 the contributor page improved.
  pages/contributor.html
  script/contributor.js
  style/contributor.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#695 Added Tutorial page explaining PDF feature extraction and model training
  Assets/projectpics/pdf_mal_detection.jpg
  pages/pdf_malware_detection.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#698 Update projects.html
  pages/projects.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#701 fixed allignment
  style/course.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#720 Updated footer design
  index.html
  pages/Testimonial.html
  pages/about.html
  pages/community_suport.html
  pages/contact.html
  pages/courses.html
  pages/feedback.html
  pages/projects.html
  style/about.css
  style/contact.css
  style/course.css
  style/style.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#724 links fixed
  index.html
  pages/Testimonial.html
  pages/about.html
  pages/community_suport.html
  pages/contact.html
  pages/courses.html
  pages/feedback.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#730 Implemented Toast Notification and Auto-Navigation for Sign Up Button
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#731 Added chatbot development project tutorial in project page
  pages/chatbot_development_tutorial.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#733 Added complete tutorial page for COVID19 facemask detection
  Assets/projectpics/facemask_detection.jpg
  pages/covid_facemask_detection.html
  pages/projects.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#739 Added urban sound classification tutorial on project page
  pages/urban_sound_classification_tutorial.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#741 Added Transfer Learning Tutorial to the project page
  Assets/projectpics/EfficientNetB0.png
  Assets/projectpics/InceptionV3.png
  Assets/projectpics/bird1.png
  Assets/projectpics/bird2.png
  Assets/projectpics/bird3.png
  Assets/projectpics/bird_species.jpg
  Assets/projectpics/graph.png
  pages/transfer_learning_tutorial.html
  script/projects.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#744 fixed logo overlap issue by increasing margin
  style/course_details.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#753 Implement_Real-Time_Email_Validation_for_Contact_Form
  pages/CSS/contact.css
  pages/contact.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#764 Fixed Suggested Bugs
  index.html
  pages/community_suport.html
  pages/contact.html
  pages/forum.html
  pages/mentor_program.html
  pages/qa_schedule.html
  pages/resources.html
  pages/social_media.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#767 Feedback page UI/UX #748
  pages/feedback.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#770 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: level1, gssoc-ext, hacktoberfest-accepted
